[tool.black]
target-version = ["py311"]

[tool.mypy]
packages = "bot30"
modules = ["current_map_updater", "mapcycle_updater"]
strict = true
warn_unreachable = true

[tool.ruff]
target-version = "py311"
line-length = 88
extend-exclude = [".*"]
extend-select = [
    "B",  # flake8-bugbear
    "E",  # pycodestyle (errors)
    "F",  # Pyflakes
    "I",   # isort
    "PL",  # Pylint
    "RUF",
    "S",  # flake8-bandit
    "T20",  # flake8-print
    "UP",  # pyupgrade
    "W",  # pycodestyle (warnings)
    "YTT",  # flake8-2020
]
